ok

diff --git a/src/bin/zinve b/src/bin/zinve
--- a/src/bin/zinve
+++ b/src/bin/zinve
@@ -1,8 +1,69 @@
 #!/usr/bin/env zsh
 
+setopt localoptions localtraps
+
 [[ $- == *"i"* ]] || set -euo pipefail ;
-. ${0:A:h}/_common.zsh
-ca-lib-load 'venv'
-ca-venv-exec-in-app-dir ipython
+
+
+if [[ ${ZINVE__CONFIG__IS_PROD_BUNDLE:-""} != "1" ]]; then
+    if [[ -z ${ZINVE__LOADER_FPATH+x} ]]; then
+        ZINVE__LOADER_FPATH=${0:A:h:h}/lib/loader.zsh
+    fi
+    if [[ -e ${ZINVE__LOADER_FPATH} ]]; then
+        . ${ZINVE__LOADER_FPATH}
+        zinve::loader::load-all-libs ;
+    else
+        echo "ERROR: SOURCE TARGET '$ZINVE__LOADER_FPATH' NOT FOUND!" >&2 ;
+        exit 1 ;
+    fi
+fi
+
+
+zinve-main-cmd::exec() {
+    zinve::venv::exec-in-venv-implicit $@ ;
+}
+zinve-main-cmd::run() {
+    zinve::venv::run-in-venv-implicit $@ ;
+}
+
+__runit() {
+    local cmdname=""
+    typeset -a py_call=()
+    local venv_name="" ;
+    local p_name=""
+    local base_d=""
+    typeset -a req_files=()
+    local curr ;
+    while [[ $# -gt 0 ]]; do
+        curr=$1 ; shift ;
+        if [[ $curr == '--' ]]; then
+            py_call+=( $@ ) ; shift $# ; break ;
+        fi
+        if [[ $curr == '-'* ]]; then
+            case $curr in
+                -p | --python ) { p_name=$1 ; shift ; continue ; } ;;
+                -n | --name ) { venv_name=$1 ; shift ; continue ; } ;;
+                -b | --base-dir ) { base_d=$1 ; shift ; continue ; } ;;
+                -r ) { req_files+=( $1 ) ; shift ; continue ; } ;;
+                * ) { zinve::fatal "unknown flag '$curr'" ; exit 1 ; } ;;
+            esac
+        else
+            if [[ $cmdname == "" ]]; then
+                cmdname=$curr ; continue ;
+            fi
+            zinve::fatal "unknown command '$curr'" ;
+        fi
+    done
+    [[ $base_d == "" ]] || ZINVE__PARAM__VENVS_BASEDIR=$base_d ;
+    [[ $p_name == "" ]] || ZINVE__PARAM__TARGET_PYTHON_BIN=$p_name ;
+    [[ $venv_name == "" ]] || ZINVE__PARAM__TARGET_NAME=$venv_name ;
+    for curr in ${req_files[@]}; do
+        ZINVE__PARAM__TARGET_REQUIREMENTS_FILES+=( $curr )
+    done
+    local cmd_func="zinve-main-cmd::${cmdname}"
+    ${cmd_func} ${py_call[@]}
+}
+
+__runit $@
 
 
